spring.application.name=eshop-khujolt-backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/eshop-khujolt
spring.datasource.username=eshop-khujolt_user

spring.docker.compose.enabled=true
spring.docker.compose.lifecycle-management=start-and-stop

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

jwt.expiration=3600000