CREATE TABLE public.categories
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    name       VARCHAR(255) NOT NULL,

    CONSTRAINT categories_pkey PRIMARY KEY (id),
    CONSTRAINT ukt8o6pivur7nn124jehx7cygw5 UNIQUE (name)
);

CREATE TABLE public.users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    email      VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name  VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    role       VARCHAR(255) NOT NULL,

    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
    CONSTRAINT users_role_check CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE public.products
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at  TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    description VARCHAR(2000),
    name        VARCHAR(255)   NOT NULL,
    price       NUMERIC(10, 2) NOT NULL,
    stock       INTEGER        NOT NULL,
    category_id BIGINT,

    CONSTRAINT products_pkey PRIMARY KEY (id),
    CONSTRAINT fkog2rp4qthbtt2lfyhfo32lsw9
        FOREIGN KEY (category_id)
            REFERENCES public.categories (id)
);