CREATE TABLE public.carts
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,

    CONSTRAINT carts_user_unique UNIQUE (user_id),
    CONSTRAINT carts_user_fk
        FOREIGN KEY (user_id)
            REFERENCES public.users (id)
);

CREATE TABLE public.cart_items
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id    BIGINT  NOT NULL,
    product_id BIGINT  NOT NULL,
    quantity   INTEGER NOT NULL,

    CONSTRAINT cart_items_quantity_check
        CHECK (quantity BETWEEN 1 AND 999),

    CONSTRAINT cart_items_cart_product_unique
        UNIQUE (cart_id, product_id),

    CONSTRAINT cart_items_cart_fk
        FOREIGN KEY (cart_id)
            REFERENCES public.carts (id)
            ON DELETE CASCADE,

    CONSTRAINT cart_items_product_fk
        FOREIGN KEY (product_id)
            REFERENCES public.products (id)
);

CREATE INDEX idx_cart_items_product_id
    ON public.cart_items (product_id);